version: '3.1'
services:
    database:
        image: 'mariadb:10.6'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=symfony-bootstrap
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '46003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '46000:80'

    php:
        build: .docker/php
        working_dir: /app
        volumes:
            - '.:/app'
            - './.docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
