name: continuous-deployment
on:
  push:
    branches:
      - develop
      - main
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
jobs:
  job0:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: Clone Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: ./.semver
      - if: github.event_name == 'push'
        name: Install NPM modules
        working-directory: ./.semver
        run: npm ci
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Bump version (release)
        working-directory: ./.semver
        run: npm run release -- --release-as='patch'


      - name: Link docker-compose.override.yml
        run: ln -s ./.github/docker-compose.override.yml .
      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker containers
        run: docker-compose up --detach
      - name: Run code lint check
        run: docker-compose exec -T app composer run-lint-check
      - name: Run code static analysis
        run: docker-compose exec -T app composer run-phpstan-analysis
      - name: Run unit tests
        run: docker-compose exec -T app composer run-unit-tests
      - name: Run functional tests
        run: docker-compose exec -T app composer run-functional-tests
      - name: Destroy Docker containers
        run: docker-compose down --volumes --remove-orphans

      - if: github.event_name == 'push'
        name: Publish Docker images
        run: docker-compose push
      - if: github.event_name == 'push'
        name: Publish version
        run: git push && git push --tags

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Deploy to production
        run: echo 'Deploying to production...'